package com.cinecom.camera;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.hardware.camera2.*;import android.hardware.camera2.params.*;import android.media.*;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    TextureView preview; TextView status,mode,values; Button record,profile; CameraDevice camera; CameraCaptureSession session; CameraCharacteristics chars; String cameraId; Recorder recorder; boolean recording=false; long selectedProfile=DynamicRangeProfiles.STANDARD; Handler handler=new Handler(Looper.getMainLooper());
    final int REQ=41;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);buildUi();if(Build.VERSION.SDK_INT>=23 && (checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED))requestPermissions(new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO},REQ);else preview.post(this::openCamera);}
    void buildUi(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);preview=new TextureView(this);root.addView(preview,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout top=new LinearLayout(this);top.setPadding(24,16,24,8);top.setGravity(Gravity.CENTER_VERTICAL);top.setOrientation(LinearLayout.HORIZONTAL); TextView logo=t("CINECOM",20,true);top.addView(logo,new LinearLayout.LayoutParams(0,60,1));status=t("CHECKING CAMERA",14,false);top.addView(status);root.addView(top,lp(-1,76,Gravity.TOP));
        LinearLayout bottom=new LinearLayout(this);bottom.setPadding(24,10,24,12);bottom.setGravity(Gravity.CENTER_VERTICAL);bottom.setBackgroundColor(0xB8000000); values=t("24 FPS   ISO AUTO   1/48   WB 5600K",15,false);bottom.addView(values,new LinearLayout.LayoutParams(0,64,1)); profile=new Button(this);profile.setText("SDR");profile.setOnClickListener(v->cycleProfile());bottom.addView(profile,new LinearLayout.LayoutParams(150,64));record=new Button(this);record.setText("●");record.setTextSize(28);record.setOnClickListener(v->toggleRecord());bottom.addView(record,new LinearLayout.LayoutParams(120,64));root.addView(bottom,lp(-1,88,Gravity.BOTTOM));setContentView(root);preview.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){openCamera();}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});}
    TextView t(String s,int size,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(size);v.setGravity(Gravity.CENTER_VERTICAL);if(bold)v.setTypeface(android.graphics.Typeface.DEFAULT,1);return v;} FrameLayout.LayoutParams lp(int w,int h,int g){FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(w,h);p.gravity=g;return p;}
    void openCamera(){try{CameraManager m=(CameraManager)getSystemService(CAMERA_SERVICE);for(String id:m.getCameraIdList()){CameraCharacteristics c=m.getCameraCharacteristics(id);Integer f=c.get(CameraCharacteristics.LENS_FACING);if(f!=null&&f==CameraCharacteristics.LENS_FACING_BACK){cameraId=id;chars=c;break;}}if(cameraId==null)throw new Exception("No rear camera");CameraCapabilities cap=new CameraCapabilities(chars);status.setText(cap.tenBit?(cap.hlg10?"10-BIT HLG10 READY":"10-BIT READY"):("8-BIT CAMERA"));m.openCamera(cameraId,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;startPreview();}public void onDisconnected(CameraDevice c){c.close();camera=null;}public void onError(CameraDevice c,int e){c.close();camera=null;}},handler);}catch(Exception e){status.setText("CAMERA ERROR: "+e.getMessage());}}
    Size chooseSize(){StreamConfigurationMap map=chars.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);Size best=null;for(Size s:map.getOutputSizes(SurfaceTexture.class)){if(s.getWidth()<=3840 && (best==null||s.getWidth()>best.getWidth()))best=s;}return best!=null?best:new Size(1920,1080);}
    void startPreview(){try{SurfaceTexture st=preview.getSurfaceTexture();Size sz=chooseSize();st.setDefaultBufferSize(sz.getWidth(),sz.getHeight());Surface ps=new Surface(st);CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);b.addTarget(ps);b.set(CaptureRequest.CONTROL_MODE,CaptureRequest.CONTROL_MODE_AUTO);camera.createCaptureSession(Collections.singletonList(ps),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession s){session=s;try{session.setRepeatingRequest(b.build(),null,handler);}catch(Exception ignored){}}public void onConfigureFailed(CameraCaptureSession s){status.setText("PREVIEW FAILED");}},handler);}catch(Exception e){status.setText("PREVIEW ERROR");}}
    void cycleProfile(){if(chars==null)return;CameraCapabilities cap=new CameraCapabilities(chars);if(selectedProfile==DynamicRangeProfiles.STANDARD && cap.hlg10)selectedProfile=DynamicRangeProfiles.HLG10;else if(selectedProfile==DynamicRangeProfiles.HLG10&&cap.hdr10)selectedProfile=DynamicRangeProfiles.HDR10;else selectedProfile=DynamicRangeProfiles.STANDARD;profile.setText(selectedProfile==DynamicRangeProfiles.HLG10?"HLG10":selectedProfile==DynamicRangeProfiles.HDR10?"HDR10":"SDR");status.setText(selectedProfile==DynamicRangeProfiles.STANDARD?"8-BIT SDR":"10-BIT "+(selectedProfile==DynamicRangeProfiles.HLG10?"HLG10":"HDR10"));}
    void toggleRecord(){if(recording)stopRecord();else startRecord();}
    void startRecord(){if(camera==null)return;try{Size sz=chooseSize();File dir=new File(getExternalFilesDir(Environment.DIRECTORY_MOVIES),"Cinecom");dir.mkdirs();File out=new File(dir,"CINE_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".mp4");boolean ten=selectedProfile!=DynamicRangeProfiles.STANDARD;recorder=new Recorder();Surface enc=recorder.start(sz.getWidth(),sz.getHeight(),24,50000000,ten,selectedProfile,out);SurfaceTexture st=preview.getSurfaceTexture();st.setDefaultBufferSize(sz.getWidth(),sz.getHeight());Surface ps=new Surface(st);CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_RECORD);b.addTarget(ps);b.addTarget(enc);b.set(CaptureRequest.CONTROL_MODE,CaptureRequest.CONTROL_MODE_AUTO);if(Build.VERSION.SDK_INT>=33&&ten)b.set(CaptureRequest.CONTROL_CAPTURE_INTENT,CaptureRequest.CONTROL_CAPTURE_INTENT_VIDEO_RECORD);OutputConfiguration po=new OutputConfiguration(ps);OutputConfiguration eo=new OutputConfiguration(enc);if(Build.VERSION.SDK_INT>=33&&ten){po.setDynamicRangeProfile(selectedProfile);eo.setDynamicRangeProfile(selectedProfile);}List<OutputConfiguration> outs=Arrays.asList(po,eo);SessionConfiguration sc=new SessionConfiguration(SessionConfiguration.SESSION_REGULAR,outs,new HandlerExecutor(handler),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession s){session=s;try{s.setRepeatingRequest(b.build(),null,handler);recording=true;record.setText("■");status.setText("REC  "+(ten?"10-BIT":"8-BIT")+"  HEVC");}catch(Exception e){stopRecord();}}public void onConfigureFailed(CameraCaptureSession s){status.setText("RECORD SESSION FAILED");recorder.stop();}});camera.createCaptureSession(sc); }catch(Exception e){status.setText("RECORD ERROR: "+e.getMessage());if(recorder!=null)recorder.stop();}}
    void stopRecord(){try{if(session!=null)session.stopRepeating();}catch(Exception ignored){}if(recorder!=null){recorder.stop();recorder=null;}recording=false;record.setText("●");status.setText("READY");startPreview();}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ)preview.post(this::openCamera);}
    static class HandlerExecutor implements java.util.concurrent.Executor{final Handler h;HandlerExecutor(Handler h){this.h=h;}public void execute(Runnable r){h.post(r);}}
}
